### PR TITLE
Release tests environment

### PR DESCRIPTION
**Pull request by acs**
Add all files needed to execute the tests before a new release.

Also, it includes the script needed to build a new release.

### CODE REVIEW

**Comment by jgbarah** [comment]
## Mordred test environment

* we should move evetything to tests, instead of releases/tests

* setup.cfg: includes passwds, and absolute directories

* projects.json:
 - why "*jenkins" and "jenkins" as entries?
 - Why "*jira" (two of them) and "jira"?
 - What is "C7LSGB0AU" in "slack"?

* cache-test.tgz
 - it unpacks to perceval-cache: it would be better if the basename of
     the file, and the directory name would be the same
 - contains data for testing: are we sure all of it is public?
 - in particular, it seems we have a spreadsheet, I'm not sure it is public...
 - I'm not sure the data for the telegram channel can be consdiered public

* docker-compose.yml:
 - shouldn't mariadb export some port?
 - or maybe not, and we could do the same for elasticsearch and kibitter?
 - as such, you need some ports available, which maybe are not in a certain host
 - mounts volumes with absolute directories

* stage:
 - should run in any properly configurated machine (now includes wired paths,
     see below)
 - should be a python directory
 - should not include absolute paths
 - installation of Python packages should be with "pip install ."
     (instead of python3 setup.py install)
 - why Python installation modules need sudo?
 - arthur seems to be a part of the test
     shouldn't it a least be optional?
 - shouldn't http://172.17.0.1:5601 be a relative address, or something?

I suggest that we start with a Python file equivalent to "stage",
that runs with proper options in a host environment correctly
set up. Then, we can include it in a docker environment.

## Panel testing

I suggest that we deal with this one in a separate pull request, once
the former is complete (or even in parallel). As I understand it,
given an ElasticSearch with the needed indexes, it should work...

**Comment by acs** [comment]
@jgb it is pretty hard to respond you to all the comments above. As we have talked this morning, we can approve the PR and start working with new PRs to work in above issues.

What do you think? You can then open new issues using the ticketing system in GitHub and we can fix them.

**Comment by jgbarah** [comment]
OK, let's do it that way. But please, try to keep the above modifications in mind to have them implemented as soon as possible.

**Comment by jgbarah** [comment]
Opened issues: #16, #17, #18, #19, #20, #21; and pull requests: #15.

**Comment by jgb** [comment]
Again @acs  please try to use @jgbarah instead of my handle here for notifications.

**Pull request merged**
